<a href="https://colab.research.google.com/github/KomalMano/Story/blob/master/12_K_Fold_Cross_Validation_eg_code.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [40]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
import numpy as np
from sklearn.datasets import load_iris

In [41]:
iris = load_iris()

In [42]:
dir(iris)

['DESCR', 'data', 'feature_names', 'filename', 'target', 'target_names']

In [43]:
from sklearn.model_selection import train_test_split

In [44]:
X_train,X_test,y_train,y_test = train_test_split(iris.data,iris.target,test_size=0.3)

In [45]:
lr = LogisticRegression()
lr.fit(X_train,y_train)
lr.score(X_test,y_test)

0.9333333333333333

In [46]:
svm = SVC()
svm.fit(X_train,y_train)
svm.score(X_test,y_test)

0.9333333333333333

In [47]:
rf = RandomForestClassifier()
rf.fit(X_train,y_train)
rf.score(X_test,y_test)

0.9555555555555556

In [48]:
dt = tree.DecisionTreeClassifier()
dt.fit(X_train,y_train)
dt.score(X_test,y_test)

0.9555555555555556

In [49]:
from sklearn.model_selection import cross_val_score

In [64]:
cross_val_score(LogisticRegression(),iris.data,iris.target,cv=3)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


array([0.98, 0.96, 0.98])

In [65]:
cross_val_score(SVC(),iris.data,iris.target,cv=3)

array([0.96, 0.98, 0.94])

In [66]:
cross_val_score(RandomForestClassifier(n_estimators=970),iris.data,iris.target, cv=3)

array([0.98, 0.94, 0.96])

In [67]:
cross_val_score(DecisionTreeClassifier(),iris.data,iris.target,cv=3)

array([0.98, 0.92, 0.98])