<a href="https://colab.research.google.com/github/KomalMano/Story/blob/master/12_K_Fold_Cross_Validation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits

In [2]:
digits = load_digits()

In [3]:
from sklearn.model_selection import train_test_split

In [4]:
X_train,X_test,y_train,y_test = train_test_split(digits.data, digits.target,test_size=0.3)

In [5]:
#now use different classifier
#the 1st classifier i m use to LogisticRegression 
lr = LogisticRegression()
lr.fit(X_train,y_train)
lr.score(X_test,y_test)
#Classifier is basically ML model which tries to classify ur samples
#and i train it using xtrain ytrain 

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


0.9666666666666667

In [6]:
#I have many other model like SVM
#Now i want to try SVM. How SVM performs
svm = SVC()
svm.fit(X_train,y_train)
svm.score(X_test,y_test)

0.987037037037037

In [7]:
#Now try random forest as well
rf = RandomForestClassifier(n_estimators=140)
rf.fit(X_train,y_train)
rf.score(X_test,y_test)
#this was a quick way of measuring the performance of these 3 models

#now thisworks in practicle situation but what happen is the distribution of samples in the X_train and X_test is not uniform right .
#when i run this method 1 more time . Now my samples will change totally 

0.9703703703703703

In [8]:

#train_test_split method have 1 problem . U can not run it only 1 time and say the particular model is better the other model . So u have to run this train_test_split multiple time.
#so every time it's changing.

#Now let's try K FOLD
#So 1st use K FOLD API demonstrate what exactly doing.
from sklearn.model_selection import KFold

In [9]:
kf = KFold(n_splits=3) #here we want to specify how many folds we will like
kf # here is created that

KFold(n_splits=3, random_state=None, shuffle=False)

In [10]:
#and the way u use this KFold on the Datasets
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]): #now my kFold is ready
  print(train_index, test_index)
  #So whrn i run this , what exactly happeing in this .kf.split() gives iterator and iterator return train and test for each of the iterations .
  #So split divided into 3 folds , 3 each. 1st iteration use 1 fold for testing which is this [0,1,2] and remaining 2 folds for training which is this [3 4 5 6 7 8].
  #In the 2nd iteration mode is to training 0 1 2 and this fold is to testing 3 4 5.
  #it repeate the procedure like that 

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [11]:
#Now we are going to use kFolds for our digits example .So to simplify the things .
#I m going to write this generic method call get_score which take model as an input. 
def get_score(model, X_train, X_test, y_train, y_test):
  model.fit(X_train,y_train) # fit mean to train our model
  return model.score(X_test, y_test) # once the training is done it will return the model score using the test sample u have supplying as an argument to this method . Now this method is prety poweful. We could have use this method to measure performance of these guys as well.


In [12]:
#Lets just quickly show u . Lets instead of repeting these 3 lines as like previous regression model svm model.
#I just call the get_score method here 
get_score(LogisticRegression(),X_train,X_test,y_train,y_test)
#It should give me the score.

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


0.9666666666666667

In [14]:
#Same could i have done for SVC here 
get_score(SVC(),X_train,X_test,y_train,y_test)
#it's just modulizing our code.

0.987037037037037

In [16]:
#So once we have this method ready.I m going to now use kFolds on our digits datasets .
from sklearn.model_selection import StratifiedKFold # StratifiedKFold is similarl to kFold .But StratifiedKFold is little bit better than that when u seperating out over folds it will divide the each of the classification categories in a uniform way and this could be very helpful.
#bcz imagine u r creating 3 folds for eg our iris dataset and 2 folds have a 2 types of flower . ! fold just an very different types of flowers then it might create a problems. That's way use StratifiedKFold is better.

#people usually use 10 splits but just to keep things simple . I m using 3 here .
folds = StratifiedKFold(n_splits=3)

In [28]:
#Onc u have ur folds ready . 
#So this method StratifiedKFold(n_splits=3) is exactly same as this KFold(n_splits=3)
#So we are doing repeating same kind of thing . But we are working on the real life eg of digits datasets .
scores_lr = [] # i wll prepare the scores array to prepare our scores of different model
scores_svm = []
scores_rf = []

# here we are doing the same exact thing in the previosly .
 # But here we use real data instead of dummy data 
for train_index,test_index in kf.split(digits.data):
  X_train,X_test,y_train,y_test = digits.data[train_index],digits.data[test_index], \
                                  digits.target[train_index],digits.target[test_index]
  #now its time to measure the performance of 3 of our model in each iteration 
  #So we have 3 folds, this for loop will gone a repeate 3 times . it will take every time xrain ytrain ytrain ytest.
  #and will measure performance of our model and then will append the scores of the empty arrays .
  #scores_lr = []
  #scores_svm = []
  #scores_rf = []
  #So that r we doing .
  scores_lr.append(get_score(LogisticRegression(),X_train,X_test,y_train,y_test))
  scores_svm.append(get_score(SVC(),X_train,X_test,y_train,y_test))
  scores_rf.append(get_score(RandomForestClassifier(n_estimators=40),X_train,X_test,y_train,y_test))
  #when i print 1st iteration 3 model perform . same as 2nd and 3rd iteration.

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression


In [29]:
#Now my scores should be ready . Now i print them
scores_lr

[0.9232053422370617, 0.9415692821368948, 0.9148580968280468]

In [30]:
scores_svm

[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]

In [31]:
scores_rf
#What u can do this u can take the avg score of these 3 and u can determine the best best model for a given problem.


[0.9365609348914858, 0.9465776293823038, 0.9131886477462438]

In [32]:
#now this appended type code is little massy bcz we have deal with so many indexes .
#But lucky sklearn lib comes up with a readymate method called CrossValScore which u can use the to do the exact same thing i did here . in append array lines.
#So this thing i wrote this code just to explain u how kFolds works.But in real life we are solving ML problem. U don't write this much code . U just call CrossValScore Method.
#Which i can demo it here right now.
from sklearn.model_selection import cross_val_score 

In [35]:
# and once the method is imported u can call this method 
#1st argument is ur classifier , 2nd is ur x and 3rd is ur y
cross_val_score(LogisticRegression(),digits.data,digits.target)
#the answer is same as like the previously 
#So internally that method did the same thing as for loopof append basically 
#it created folds and measure the performance and it repare the codes array 


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression


array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [36]:
#i will now call the same method on my SVM classifier 
cross_val_score(SVC(),digits.data,digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [39]:
#in my 3rd case
cross_val_score(RandomForestClassifier(n_estimators=40),digits.data,digits.target)
#it just do that in 1 line man . ML is not hard . If u know the inernal of these libraries then all u need to do is just call 1 single method .
#and its measuring the performance .
#we compared different classifiers. u can compare same classifier with different parameters. This is called parameter tunning.
#For ef we have RandomForestClassifier. we run with 40 trees . 
 

array([0.93888889, 0.91111111, 0.95543175, 0.96657382, 0.91086351])

In [42]:
#We actually run the same classifier with let say 5 trees the score will down the little bit.
cross_val_score(RandomForestClassifier(n_estimators=5),digits.data,digits.target)


array([0.87222222, 0.75277778, 0.89972145, 0.92479109, 0.86350975])

In [44]:
#let we try 15 for eg
cross_val_score(RandomForestClassifier(n_estimators=15),digits.data,digits.target)
#and the score will little bit up

array([0.91666667, 0.90555556, 0.93036212, 0.94707521, 0.89415042])

In [46]:
#So look like as increase my trees my score is increasing
cross_val_score(RandomForestClassifier(n_estimators=50),digits.data,digits.target)
#So in this way u can take a model and do parameter tuning . 
#So use the same algorithm basically here RandomForestClassifier
#But tunning the parameters and trying to guage which 1 deliver the best 1 performance 
#So u can see that cross validation technique is prety useful.
#It not only allows u to compare different algorithms. But same algorithms with different parameters . How it would be have for ur given problem.
#It can tell u that.
#So ML is not a scientific eq where for given problem u use this model verses that model something a little bit like trial and error based .
#For ur given prolem and given data set u need to try a vrious model with various parameters and then figure out which one is best for one use case 


array([0.91666667, 0.89444444, 0.96657382, 0.96100279, 0.91643454])