<a href="https://colab.research.google.com/github/KomalMano/Story/blob/master/3_Linear_Regression_Multiple_Variables.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
from google.colab import files
import numpy as np
from sklearn import linear_model
import io

In [4]:
uploaded = files.upload()

Saving home.csv to home.csv


In [5]:
for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn, length=len(uploaded[fn])))

User uploaded file "home.csv" with length 113 bytes


In [6]:
uploaded

{'home.csv': b'area,bedrooms,age,price\r\n2600,3,20,550000\r\n3000,4,15,565000\r\n3200,,18,610000\r\n3600,3,30,595000\r\n4000,5,8,760000\r\n'}

In [9]:
df = pd.read_csv(io.StringIO(uploaded['home.csv'].decode('utf-8')))
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [10]:
# above NaN null data now need to handle it. I will take this median of entire column  and put it here.
#now calculate median
df.bedrooms.median()

3.5

In [12]:
#now i want to take the integer value instead of float
import math
median_bedrooms = math.floor(df.bedrooms.median())
median_bedrooms

3

In [13]:
#now fill bedroom col NaN values using fillna function
df.bedrooms.fillna(median_bedrooms)

0    3.0
1    4.0
2    3.0
3    3.0
4    5.0
Name: bedrooms, dtype: float64

In [15]:
#above we get new series instead NaN value 
#now replace with median number 
#i need to assign this back to orignal series 
df.bedrooms = df.bedrooms.fillna(median_bedrooms)
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       3.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [18]:
#so my data pre procees is over again so before applying ML model to preprocess model. u need to clean ur data .So ur data is massy fix the error . then apply the ML model that data u train the model.
reg = linear_model.LinearRegression() # create reg class object
reg.fit(df[['area','bedrooms','age']],df.price) #create fit method is used to train ur model using ur training set . Here is my training set is ... 
#so our target set is price. Now my model is ready

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [19]:
reg.coef_ # price=m1*area+m2*bedrooms+m3*age+b coefficient is m1,m2,m3

array([   137.25, -26025.  ,  -6825.  ])

In [21]:
reg.intercept_ #intercept is another variable b == price=m1*area+m2*bedrooms+m3*age+b

383724.99999999994

In [23]:
#now calculae the price
reg.predict([[3000,3,40]]) #3000 price , 3 bedrooms , 40 years old

array([444400.])

In [24]:
reg.predict([[3000,4,15]])

array([589000.])

In [26]:
#now calculate 1st price 
#price=m1*area+m2*bedrooms+m3*age+b
137.25*3000+-26025*3+40*-6825+383724.99999999994

444399.99999999994

In [27]:
reg.predict([[2500,4,5]])

array([588625.])