<a href="https://colab.research.google.com/github/KomalMano/Story/blob/master/5_Save_Model_Using_Joblib_And_Pickle.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model
from google.colab import files
import io

In [17]:
uploaded = files.upload()

Saving home.csv to home (1).csv


In [18]:
for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn, length=len(uploaded[fn])))

User uploaded file "home.csv" with length 113 bytes


In [19]:
uploaded

{'home.csv': b'area,bedrooms,age,price\r\n2600,3,20,550000\r\n3000,4,15,565000\r\n3200,,18,610000\r\n3600,3,30,595000\r\n4000,5,8,760000\r\n'}

In [20]:
df = pd.read_csv(io.StringIO(uploaded['home.csv'].decode('utf-8')))
df.head()

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [21]:
model = linear_model.LinearRegression()
model.fit(df[['area']],df.price)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [22]:
model.coef_

array([134.07534247])

In [23]:
model.intercept_

176232.87671232875

In [24]:
model.predict([[5000]])

array([846609.5890411])

In [25]:
import pickle
#pickle model is use to serialies ur python object into ur file

In [26]:
#so here i will use the file
with open('model_pickle','wb') as f:
  pickle.dump(model,f) #dump my model into this file

In [27]:
with open('model_pickle','rb') as f: #so again i have to write open file pointer,Same as but in read mode.As binary supplied so i has  write b here.
  mp = pickle.load(f) #I am use the pickle dump load file
  #now i have my file loaded to into a memory and here mp is object.

In [29]:
mp.predict([[5000]])
#now here we can say that there is a train model and train brain. u can use it. u can ask the question and give the answer.

array([846609.5890411])

In [30]:
#there is a 2nd approch of saving model to a file which is using sklearn joblib .
#when u go google sklearn model persistence .
#if u consist of large numpy arrays then joblib might be more efficient. but joblib give u same functionality .
from sklearn.externals import joblib

/usr/local/lib/python3.7/dist-packages/sklearn/externals/joblib/__init__.py:15: FutureWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=FutureWarning)


In [31]:
#diff joblib and pickle api 
#joblib drive file name directly 
joblib.dump(model,'model_joblib')

['model_joblib']

In [32]:
mj = joblib.load('model_joblib')

In [33]:
mj.predict([[5000]])

array([846609.5890411])

In [34]:
#binary thing such as different thing 
mj.coef_

array([134.07534247])

In [35]:
mj.intercept_

176232.87671232875