<a href="https://colab.research.google.com/github/KomalMano/Story/blob/master/6_Dummy_Variables_%26_One_Hot_Encoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [37]:
import pandas as pd
import numpy as np
from sklearn import linear_model
from google.colab import files
import io

In [38]:
uploaded = files.upload()

Saving town_area.csv to town_area (1).csv


In [39]:
for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn, length=len(uploaded[fn])))

User uploaded file "town_area.csv" with length 370 bytes


In [40]:
uploaded

{'town_area.csv': b'town,area,price\r\nmonroe township,2600,550000\r\nmonroe township,3000,565000\r\nmonroe township,3200,610000\r\nmonroe township,3600,680000\r\nmonroe township,4000,725000\r\nwest windsor,2600,585000\r\nwest windsor,2800,615000\r\nwest windsor,3300,650000\r\nwest windsor,3600,710000\r\nrobbinsville,2600,575000\r\nrobbinsville,2900,600000\r\nrobbinsville,3100,620000\r\nrobbinsville,3600,695000\r\n'}

In [41]:
df = pd.read_csv(io.StringIO(uploaded['town_area.csv'].decode('utf-8')))
df

town  area   price
0   monroe township  2600  550000
1   monroe township  3000  565000
2   monroe township  3200  610000
3   monroe township  3600  680000
4   monroe township  4000  725000
5      west windsor  2600  585000
6      west windsor  2800  615000
7      west windsor  3300  650000
8      west windsor  3600  710000
9      robbinsville  2600  575000
10     robbinsville  2900  600000
11     robbinsville  3100  620000
12     robbinsville  3600  695000

In [42]:
#the 1st step i am going to take to create those dummy column
#pandas has this dummy and which will return the dummy variable column
dummies = pd.get_dummies(df.town)
dummies

monroe township  robbinsville  west windsor
0                 1             0             0
1                 1             0             0
2                 1             0             0
3                 1             0             0
4                 1             0             0
5                 0             0             1
6                 0             0             1
7                 0             0             1
8                 0             0             1
9                 0             1             0
10                0             1             0
11                0             1             0
12                0             1             0

In [43]:
#now the 2nd step to concatenate the dummy data frame with my orignal data frame
merged = pd.concat([df,dummies],axis='columns')
merged

town  area   price  monroe township  robbinsville  west windsor
0   monroe township  2600  550000                1             0             0
1   monroe township  3000  565000                1             0             0
2   monroe township  3200  610000                1             0             0
3   monroe township  3600  680000                1             0             0
4   monroe township  4000  725000                1             0             0
5      west windsor  2600  585000                0             0             1
6      west windsor  2800  615000                0             0             1
7      west windsor  3300  650000                0             0             1
8      west windsor  3600  710000                0             0             1
9      robbinsville  2600  575000                0             1             0
10     robbinsville  2900  600000                0             1             0
11     robbinsville  3100  620000                0             1             0
12     robbinsville  3600  695000                0             1             0

In [44]:
#now here drop the town column
final = merged.drop(['town','west windsor'],axis='columns')
final

area   price  monroe township  robbinsville
0   2600  550000                1             0
1   3000  565000                1             0
2   3200  610000                1             0
3   3600  680000                1             0
4   4000  725000                1             0
5   2600  585000                0             0
6   2800  615000                0             0
7   3300  650000                0             0
8   3600  710000                0             0
9   2600  575000                0             1
10  2900  600000                0             1
11  3100  620000                0             1
12  3600  695000                0             1

In [45]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()

In [46]:
#now i have to give x and y for training 
#x is my area and y is my price
X = final.drop('price', axis='columns')
X

area  monroe township  robbinsville
0   2600                1             0
1   3000                1             0
2   3200                1             0
3   3600                1             0
4   4000                1             0
5   2600                0             0
6   2800                0             0
7   3300                0             0
8   3600                0             0
9   2600                0             1
10  2900                0             1
11  3100                0             1
12  3600                0             1

In [47]:
#and y is nothing column
y = final.price
y

0     550000
1     565000
2     610000
3     680000
4     725000
5     585000
6     615000
7     650000
8     710000
9     575000
10    600000
11    620000
12    695000
Name: price, dtype: int64

In [48]:
#now my x and y is ready now training 
#model. fit means training ur machine learning model
model.fit(X,y)
#in here we have less data so it take less time but in training data is too much huge


LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [49]:
model.predict([[2800,0,1]]) #robin

array([590775.63964739])

In [50]:
model.predict([[3400,0,0]]) #west windsor

array([681241.66845839])

In [51]:
#if u know how ur model is accurate?
model.score(X,y)
#if my model is 1 means perfect and 95 means my model is accurate 95%

0.9573929037221873

In [52]:
#same thing is done to check my model accurate in sklearn
df

town  area   price
0   monroe township  2600  550000
1   monroe township  3000  565000
2   monroe township  3200  610000
3   monroe township  3600  680000
4   monroe township  4000  725000
5      west windsor  2600  585000
6      west windsor  2800  615000
7      west windsor  3300  650000
8      west windsor  3600  710000
9      robbinsville  2600  575000
10     robbinsville  2900  600000
11     robbinsville  3100  620000
12     robbinsville  3600  695000

In [53]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [20]:
#create new data frame
#dfle = df
# le.fit_transform(dfle.town) #fit transform means label column. So it will return the labels
#

In [54]:
#we dont want to need the array just need column
dfle = df
dfle.town = le.fit_transform(dfle.town)
dfle

town  area   price
0      0  2600  550000
1      0  3000  565000
2      0  3200  610000
3      0  3600  680000
4      0  4000  725000
5      2  2600  585000
6      2  2800  615000
7      2  3300  650000
8      2  3600  710000
9      1  2600  575000
10     1  2900  600000
11     1  3100  620000
12     1  3600  695000

In [55]:
#now next step is to create my variable
#x is my training data set and y is my dependent variable
X = dfle[['town','area']].values
X # x i want to be my 2D array and not a data frame

array([[   0, 2600],
       [   0, 3000],
       [   0, 3200],
       [   0, 3600],
       [   0, 4000],
       [   2, 2600],
       [   2, 2800],
       [   2, 3300],
       [   2, 3600],
       [   1, 2600],
       [   1, 2900],
       [   1, 3100],
       [   1, 3600]])

In [56]:
y = dfle.price
y

0     550000
1     565000
2     610000
3     680000
4     725000
5     585000
6     615000
7     650000
8     710000
9     575000
10    600000
11    620000
12    695000
Name: price, dtype: int64

In [57]:
###now create dummy variables
#from sklearn.preprocessing import OneHotEncoder #now create sk hot encoder
#ohe = OneHotEncoder(categories = 'auto', sparse=False)
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer(
    [('one_hot_encoder', OneHotEncoder(categories='auto'), [0])],
    remainder='passthrough' 
)

In [58]:
#the x is the last value which we generated
X = ct.fit_transform(X)
X

array([[1.0e+00, 0.0e+00, 0.0e+00, 2.6e+03],
       [1.0e+00, 0.0e+00, 0.0e+00, 3.0e+03],
       [1.0e+00, 0.0e+00, 0.0e+00, 3.2e+03],
       [1.0e+00, 0.0e+00, 0.0e+00, 3.6e+03],
       [1.0e+00, 0.0e+00, 0.0e+00, 4.0e+03],
       [0.0e+00, 0.0e+00, 1.0e+00, 2.6e+03],
       [0.0e+00, 0.0e+00, 1.0e+00, 2.8e+03],
       [0.0e+00, 0.0e+00, 1.0e+00, 3.3e+03],
       [0.0e+00, 0.0e+00, 1.0e+00, 3.6e+03],
       [0.0e+00, 1.0e+00, 0.0e+00, 2.6e+03],
       [0.0e+00, 1.0e+00, 0.0e+00, 2.9e+03],
       [0.0e+00, 1.0e+00, 0.0e+00, 3.1e+03],
       [0.0e+00, 1.0e+00, 0.0e+00, 3.6e+03]])

In [59]:
#now here drop the column
# ;, means take all the rows # take all the columns from index 1 on whats 
X = X[:,1:]
X

array([[0.0e+00, 0.0e+00, 2.6e+03],
       [0.0e+00, 0.0e+00, 3.0e+03],
       [0.0e+00, 0.0e+00, 3.2e+03],
       [0.0e+00, 0.0e+00, 3.6e+03],
       [0.0e+00, 0.0e+00, 4.0e+03],
       [0.0e+00, 1.0e+00, 2.6e+03],
       [0.0e+00, 1.0e+00, 2.8e+03],
       [0.0e+00, 1.0e+00, 3.3e+03],
       [0.0e+00, 1.0e+00, 3.6e+03],
       [1.0e+00, 0.0e+00, 2.6e+03],
       [1.0e+00, 0.0e+00, 2.9e+03],
       [1.0e+00, 0.0e+00, 3.1e+03],
       [1.0e+00, 0.0e+00, 3.6e+03]])

In [60]:
# in 4 values i droped this 1 column in previous line
# now my x and y is ready now training on my model
model.fit(X,y) #now my model is ready 

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [61]:
model.predict([[1,0,2800]])

array([590775.63964739])

In [62]:
model.predict([[0,1,3400]])

array([681241.6684584])

In [ ]:
#U just saw 2 dumy variables.
#1 was pandas
#2 was sklearn.preprocessing 1 hot encoder lib